"use client"
// Auto-generated by boneyard vite plugin — do not edit
import { registerBones } from 'boneyard-js/react'

import _chat_list from './chat-list.bones.json'
import _chat_messages from './chat-messages.bones.json'
import _chat_info_sidebar from './chat-info-sidebar.bones.json'
import _group_info from './group-info.bones.json'
import _search_results from './search-results.bones.json'
import _add_contact_results from './add-contact-results.bones.json'

registerBones({
  "chat-list": _chat_list,
  "chat-messages": _chat_messages,
  "chat-info-sidebar": _chat_info_sidebar,
  "group-info": _group_info,
  "search-results": _search_results,
  "add-contact-results": _add_contact_results,
})
